# Generated by Django 2.2 on 2019-04-27 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('highest_degree_earned', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('skill_1', models.CharField(max_length=20)),
                ('skill_2', models.CharField(blank=True, max_length=20)),
                ('skill_3', models.CharField(blank=True, max_length=20)),
                ('skill_4', models.CharField(blank=True, max_length=20)),
                ('skill_5', models.CharField(blank=True, max_length=20)),
                ('skill_6', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default='')),
                ('linkedIn', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('hackerRank', models.URLField(blank=True, default='')),
                ('medium', models.URLField(blank=True, default='')),
                ('quora', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, default='', max_length=200)),
                ('project_description', models.TextField(blank=True, default='')),
                ('from_date', models.DateTimeField(blank=True)),
                ('to_date', models.DateTimeField(blank=True)),
                ('test_score', models.CharField(blank=True, max_length=100)),
                ('test_description', models.TextField(blank=True)),
                ('test_date', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
