# Generated by Django 2.2 on 2019-04-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(default=2020),
        ),
    ]
