# Generated by Django 2.2 on 2019-05-06 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190427_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
