# Generated by Django 2.2 on 2019-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='from_date',
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='from_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='test_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='to_date',
            field=models.DateField(),
        ),
    ]
