# Generated by Django 2.2 on 2019-05-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190507_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
