# Generated by Django 2.2 on 2019-05-19 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190518_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
