# Generated by Django 2.2 on 2019-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_project_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
