# Generated by Django 2.2 on 2019-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='college_university',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
