# Generated by Django 2.2 on 2019-06-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20190630_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='to_date',
        ),
    ]
