# Generated by Django 2.2 on 2019-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_personalinformation_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishments',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accomplishments',
            name='to_date',
            field=models.DateField(),
        ),
    ]
