# Generated by Django 2.2 on 2019-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190630_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.DateField(),
        ),
    ]
