# Generated by Django 2.2 on 2019-06-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_personalinformation_college_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='course',
        ),
    ]
