# Generated by Django 2.2 on 2019-07-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20190721_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='photos/User.jpg', upload_to='photos/profile_pictures/'),
        ),
    ]
