# Generated by Django 2.2 on 2019-07-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20190721_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/media/user.gif', upload_to='photos/profile_pictures/'),
        ),
    ]
