# Generated by Django 2.2 on 2019-05-19 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('skill_1', models.CharField(max_length=20)),
                ('skill_2', models.CharField(blank=True, max_length=20)),
                ('skill_3', models.CharField(blank=True, max_length=20)),
                ('skill_4', models.CharField(blank=True, max_length=20)),
                ('photo_1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('link_1', models.URLField(blank=True)),
                ('link_2', models.URLField(blank=True)),
                ('link_3', models.URLField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(max_length=30)),
                ('team_size', models.IntegerField()),
                ('resume_inclusion', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True)),
                ('upload_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
