# Generated by Django 2.2 on 2019-05-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190519_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_size',
        ),
    ]
