# Generated by Django 2.2 on 2019-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume_inclusion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
