# Generated by Django 2.2 on 2019-05-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190525_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
