# Generated by Django 2.2 on 2019-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190525_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
