# Generated by Django 2.2 on 2019-06-29 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
