# Generated by Django 2.2 on 2019-06-22 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sending_user_id', models.IntegerField()),
                ('receiving_user_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sending_user_id', models.IntegerField()),
                ('receiving_user_id', models.IntegerField()),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
    ]
