# Generated by Django 2.2 on 2019-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='sending_user_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='sending_user_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='sending_user_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='sending_user_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
