# Generated by Django 2.2 on 2019-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190622_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='sending_user_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='sending_user_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='sending_user_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='sending_user_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
