# Generated by Django 2.2 on 2019-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20190623_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedproject',
            name='project_id',
            field=models.IntegerField(blank=True),
        ),
    ]
