# Generated by Django 2.2 on 2019-06-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20190623_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedproject',
            name='message',
            field=models.CharField(default='has accepted your project request for the project', max_length=50),
        ),
        migrations.AlterField(
            model_name='accepteduser',
            name='message',
            field=models.CharField(default='has accepted your connection request', max_length=50),
        ),
    ]
