# Generated by Django 2.2 on 2019-07-13 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20190629_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='has requested to join your project', max_length=50)),
                ('receiver_id', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=30)),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_picture', models.ImageField(upload_to='')),
                ('project_name', models.CharField(max_length=70)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SentUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='has sent you a connection request', max_length=50)),
                ('receiver_id', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=30)),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_picture', models.ImageField(upload_to='')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
